idf_component_register(SRCS 
                    "main.c"
                    "camara_driver/camara_driver.c"
                    "comunicacion_uart/uart_comm.c"
                    "vision_core/vision_core.c"
                    "wifi_stream/http_stream.c"
                    "proceso_qr/qr_processor.c"
                    INCLUDE_DIRS 
                    "."
                    "comunicacion_uart"
                    "vision_core"
                    "wifi_stream"
                    "camara_driver"
                    "include"
                    "proceso_qr"
                    EMBED_TXTFILES
                    "index.html"
                    REQUIRES
                    esp32-camera esp_psram esp_wifi nvs_flash esp_http_server)
